_BASE_: "Base-RCNN-VoVNet-FPN.yaml"
OUTPUT_DIR: "/home/jsalvador/RPN_DLA/datasets/VORAU/integrated_ImangeNet/output"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/8xl0cb3jj51f45a/vovnet57_ese_detectron2.pth?dl=1"
  MASK_ON: True
  VOVNET:
    CONV_BODY : "V-57-eSE"
   ROI_HEADS:
    NUM_CLASSES: 4
  RETINANET:
    NUM_CLASSES: 4
  SEM_SEG_HEAD:
    NUM_CLASSES: 4
DATASETS:
  DLA:
    REGISTER_NEW_DATASET: True
    TRAIN:
      NAME: "VORAU_train"
      JSON: "/home/jsalvador/RPN_DLA/datasets/VORAU/train_all/annotations/train_annotations.json"
      PATH: "/home/jsalvador/RPN_DLA/datasets/VORAU/train_all/"
    TEST:
      NAME: "VORAU_test"
      JSON: "/home/jsalvador/RPN_DLA/datasets/VORAU/test/annotations/test_annotations.json"
      PATH: "/home/jsalvador/RPN_DLA/datasets/VORAU/test/"
  TEST:
  - VORAU_test
  TRAIN:
  - VORAU_train

